[widget] refactor jln-fzf-files
- Replace disable-recursive with recursive-directory option.
- Add insert-prefix option.
- Detecting a parameter under the cursor is no longer done by checking for a space,
  as this does not work if it is preceded by a backslash.
- Star globbing insertion under the cursor now only occurs if
  it is at the end of the parameter or if no results are found.

diff --git a/widgets/jln-fzf-files b/widgets/jln-fzf-files
--- a/widgets/jln-fzf-files
+++ b/widgets/jln-fzf-files
@@ -1,17 +1,21 @@
 #!/usr/bin/env zsh
 
-# Insert a list of selected files with fzf
+# Insert a list of selected files with fzf.
 #
-# If anything other than a space is to the left of the cursor,
-# it will be used as the search path.
+# If there is no parameter under the cursor, the files selected via *.
 #
-# The default pattern matches all files, but glob qualifier can be configured as
+# If a parameter is below the cursor,
+# it will be expanded and then used as a file list.
+# If the cursor is at the end of the parameter * will be added before.
 #
-#   # directory only
+# The default pattern matches all files not recursively,
+# but glob qualifier can be configured as
+#
+#   # directory only (e.g. *(/))
 #   zstyle :jln-fzf-files glob-qualifiers '/'
 #
-#   # no recursive search
-#   zstyle :jln-fzf-files disable-recursive 1
+#   # recursive search (use **/* instead of *)
+#   zstyle :jln-fzf-files recursive-directory 1
 #
 # The default selector (jln-fzf-color-selector) uses fzf and ls for the color.
 # The jln-fzf-selector does not use ls.
@@ -23,11 +27,19 @@
 #   # case-insensitive match for fzf
 #   zstyle :jln-fzf-files fzf-params -i
 #
+# If the files are expanded using a parameter under the cursor,
+# a prefix can be added to the fzf query.
+# The prefix search is rudimentary and
+# may be truncated if it contains '?*<({['.
+#
+#   # add prefix in fzf query
+#   zstyle :jln-fzf-files insert-prefix 1
+#
 # If needed, you can specify your own function.
 # $prefix and $files will be predefined variables.
 # The final string must be put in the variable REPLY.
 #
-#   zstyle :jln-fzf-files selector my-selector
+#   zstyle :jln-fzf-files selector my-selector-function
 #
 # Note also that the style is looked up based on the widget name, so you
 # can bind this function to different widgets to use different patterns:
@@ -35,6 +47,8 @@
 #   zle -N fzf-directories jln-fzf-files
 #   zstyle :fzf-directories glob-qualifiers '/'
 #   bindkey '\e=' fzf-directories
+
+emulate -L zsh -o extendedglob
 
 jln-fzf-selector() {
   if [[ -n $prefix ]]; then
@@ -46,9 +60,9 @@ jln-fzf-selector() {
 
 jln-fzf-color-selector() {
   if [[ -n $prefix ]]; then
-    REPLY=${(j: :)${(qf)"$(command ls $=ls_params --color -1d -- $files | fzf -m --ansi +s $=fzf_params -q $prefix)"}}
+    REPLY=${(j: :)${(qf)"$(command ls $=ls_params -1d --color -- $files | fzf -m --ansi +s $=fzf_params -q $prefix)"}}
   else
-    REPLY=${(j: :)${(qf)"$(command ls $=ls_params --color -1d -- $files | fzf -m --ansi +s $=fzf_params)"}}
+    REPLY=${(j: :)${(qf)"$(command ls $=ls_params -1d --color -- $files | fzf -m --ansi +s $=fzf_params)"}}
   fi
 }
 
@@ -61,111 +75,102 @@ jln-fzf-size-selector() {
   REPLY=${(j: :)${(q)REPLY/(#s)[ ]#[^ ]# /}}
 }
 
-jln-fzf-files() {
-  emulate -L zsh -o extendedglob
+local REPLY glob_qualifiers recursive_directory selector ls_params fzf_params insert_prefix
+local -a files prefix
 
-  local REPLY dir glob_qualifiers disable_recursive selector ls_params fzf_params
-  local -a files dirs prefix
+zstyle -s :$WIDGET glob-qualifiers glob_qualifiers
+zstyle -s :$WIDGET recursive-directory recursive_directory
+zstyle -s :$WIDGET selector selector
+zstyle -s :$WIDGET ls-params ls_params
+zstyle -s :$WIDGET fzf-params fzf_params
+selector=${selector:-jln-fzf-color-selector}
 
-  zstyle -s :$WIDGET glob-qualifiers glob_qualifiers
-  zstyle -s :$WIDGET disable-recursive disable_recursive
-  zstyle -s :$WIDGET selector selector
-  zstyle -s :$WIDGET ls-params ls_params
-  zstyle -s :$WIDGET fzf-params fzf_params
-  glob_qualifiers="N$glob_qualifiers"
-  selector=${selector:-jln-fzf-color-selector}
+local -i start_cursor_param=${#LBUFFER%%${${(Z:n:)LBUFFER}[-1]}}
 
-  if [[ ${LBUFFER[-1]} = ' ' ]] ; then
-    if [[ $disable_recursive = 1 ]]; then
-      files=(*($glob_qualifiers))
-    else
-      files=(**/*($glob_qualifiers))
-    fi
-
-    if (( $#files == 0 )); then
-      zle -M 'no matches found'
-      return 1
-    fi
-    $selector && LBUFFER+=$REPLY
-
-  elif [[ $disable_recursive = 0 ]]; then
-    local tail=${${(Z:n:)LBUFFER}[-1]}
-    eval "files=($tail(NoN))"
-
-    if (( $#files == 0 )); then
-      zle -M 'no matches found'
-      return 1
-    fi
-
-    if [[ $c = / ]] || [[ ( $c = \' || $c = \" ) && ${tail[-2]} = / ]] ; then
-      prefix=$tail
-    fi
-
-    $selector && LBUFFER=${LBUFFER:0:-$#tail}$REPLY
-
+# no parameter under the cursor
+if (( start_cursor_param == CURSOR )) && [[ $BUFFER[$CURSOR+1] != [^[:space:]] ]]; then
+  if [[ $recursive_directory == 1 ]]; then
+    files=(**/*(N$glob_qualifiers))
   else
-    local found c tail=${${(Z:n:)LBUFFER}[-1]}
-    local -i ntail=$#tail
-
-    c=${tail[-1]}
-    # is directory: xxx/ or 'xxx/' or "xxx/"
-    if [[ $c = / ]] || [[ ( $c = \' || $c = \" ) && ${tail[-2]} = / ]] ; then
-      eval "dirs=($tail(NoN))"
-      if (( $#dirs != 0 )) ; then
-        found=x
-      else
-        eval "dirs=($tail*(NoN))"
-      fi
-    else
-      eval "dirs=($tail*(NoN))"
-    fi
-
-    if (( $#dirs == 1 )); then
-      files=($dirs**/*($glob_qualifiers))
-      if (( $#files == 0 )) ; then
-        files=($dirs($glob_qualifiers))
-        tail=$dirs[1]
-      elif [[ ${dirs[1][-1]} = / ]] ; then
-        tail=$dirs[1]
-      else
-        tail=$dirs[1]/
-      fi
-      found=x
-    elif (( $#dirs > 1 )); then
-      local -i n=0
-      for dir in $dirs ; do
-        files+=($dir**/*($glob_qualifiers))
-        if (( n == $#files )) ; then
-          files+=($dir($glob_qualifiers))
-        fi
-        n=$#files
-      done
-
-      [[ -z $found ]] || tail=''
-    fi
-
-    if (( $#files == 0 )); then
-      zle -M 'not matches found'
-      return 1
-    fi
-
-    if [[ -n $found ]]; then
-      prefix=$tail
-    else
-      local head=$tail:h
-      until [[ -d $head ]]; do
-        head=$head:h
-      done
-
-      if [[ $head != '.' ]]; then
-        prefix=$head
-      fi
-    fi
-
-    $selector && LBUFFER=${LBUFFER:0:-$ntail}$REPLY
+    files=(*(N$glob_qualifiers))
   fi
 
-  zle redisplay
-}
+  if (( $#files == 0 )); then
+    zle -M 'No matches found.'
+    return 1
+  fi
 
-jln-fzf-files "$@"
+  $selector && LBUFFER+=$REPLY
+
+# expand parameter under the cursor
+else
+  files=(${(Z:n:)${BUFFER:$start_cursor_param}})
+  local word=$files[1] glob
+  local -i nword=$#word
+
+  # if positioned at the end of the parameter
+  if (( $start_cursor_param + $#word == $CURSOR )); then
+    # if does not end with globbing, insert *
+    if [[ $word[-1] != ['?*>)'] ]] \
+    || ( [[ $word[-1] == ['?*)'] ]] && (( ($#word - ${#word%%'\'#['?*)']}) % 2 == 0 )) ) \
+    || ( [[ $word[-2] == '\' && $word[-1] == '>' ]] )
+    then
+      if [[ $recursive_directory == 1 ]]; then
+        glob='**/*'
+      else
+        glob='*'
+      fi
+    fi
+  fi
+
+  eval files="($word$glob(N$glob_qualifiers))"
+
+  if (( $#files == 0 )); then
+    # if positioned in a parameter, insert * then retry
+    if (( $start_cursor_param + $#word != $CURSOR )); then
+      if [[ $recursive_directory == 1 ]]; then
+        glob='**/*'
+      else
+        glob='*'
+      fi
+      eval files="(${word:0:$CURSOR-$start_cursor_param}*${word:$CURSOR-$start_cursor_param}$glob(N$glob_qualifiers))"
+    fi
+
+    if (( $#files == 0 )); then
+      zle -M 'No matches found.'
+      return 1
+    fi
+  fi
+
+  zstyle -s :$WIDGET insert-prefix insert_prefix
+
+  if [[ $insert_prefix == 1 ]]; then
+    # extract left chars
+    prefix=${(Q)BUFFER:$start_cursor_param:$((CURSOR-start_cursor_param))}
+    # remove characters if there is a pattern
+    prefix=${prefix/[?*<]*/}
+    # not a prefix
+    if [[ $files[1] != $prefix* ]]; then
+      # remove characters if there is a glob qualifier
+      prefix=${prefix/[\(\{]*/}
+      # not a prefix
+      if [[ $files[1] != $prefix* ]]; then
+        # remove characters if there is a group pattern
+        prefix=${prefix/[\[]*/}
+        # not a prefix => reset prefix
+        if [[ $files[1] != $prefix* ]]; then
+          prefix=
+        fi
+      fi
+    fi
+  fi
+
+  if $selector ; then
+    if ((CURSOR != start_cursor_param)); then
+      RBUFFER=${RBUFFER:$((nword-CURSOR+start_cursor_param))}
+    fi
+    LBUFFER=${LBUFFER:0:$start_cursor_param}$REPLY
+  fi
+fi
+
+zle redisplay
